# Generated by Django 4.2.1 on 2024-07-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('creation_year', models.PositiveBigIntegerField(verbose_name='Год создания')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Код')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='CarTranslatedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_names', to='cars.car')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_names', to='cars.language')),
            ],
        ),
    ]
